-- ============================================================
-- Indian Stocks Seed Data (FIXED - no duplicate yahoo_symbols)
-- Uses CTE with DISTINCT ON to handle any remaining duplicates
-- Run this in Supabase SQL Editor
-- ============================================================

-- Step 1: Create table (safe to re-run)
CREATE TABLE IF NOT EXISTS indian_stocks (
  id          SERIAL PRIMARY KEY,
  symbol      TEXT NOT NULL,
  yahoo_symbol TEXT NOT NULL,
  company_name TEXT NOT NULL,
  exchange    TEXT NOT NULL CHECK (exchange IN ('NSE','BSE','NSE,BSE')),
  sector      TEXT,
  industry    TEXT,
  series      TEXT DEFAULT 'EQ',
  created_at  TIMESTAMPTZ DEFAULT NOW()
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_is_yahoo_symbol ON indian_stocks(yahoo_symbol);
CREATE INDEX IF NOT EXISTS idx_is_symbol   ON indian_stocks(symbol);
CREATE INDEX IF NOT EXISTS idx_is_exchange ON indian_stocks(exchange);
CREATE INDEX IF NOT EXISTS idx_is_sector   ON indian_stocks(sector);
CREATE INDEX IF NOT EXISTS idx_is_search   ON indian_stocks
  USING GIN (to_tsvector('english', company_name || ' ' || symbol));

-- Step 2: Insert data (CTE deduplicates by yahoo_symbol first)
WITH raw_data (symbol, yahoo_symbol, company_name, exchange, sector, industry) AS (
  VALUES
  -- NIFTY 50
  ('RELIANCE',   'RELIANCE.NS',   'Reliance Industries Ltd',              'NSE,BSE','Energy',               'Oil & Gas Refining'),
  ('TCS',        'TCS.NS',        'Tata Consultancy Services Ltd',        'NSE,BSE','Technology',           'IT Services'),
  ('HDFCBANK',   'HDFCBANK.NS',   'HDFC Bank Ltd',                        'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('INFY',       'INFY.NS',       'Infosys Ltd',                          'NSE,BSE','Technology',           'IT Services'),
  ('ICICIBANK',  'ICICIBANK.NS',  'ICICI Bank Ltd',                       'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('HINDUNILVR', 'HINDUNILVR.NS', 'Hindustan Unilever Ltd',               'NSE,BSE','FMCG',                 'Consumer Goods'),
  ('BHARTIARTL', 'BHARTIARTL.NS', 'Bharti Airtel Ltd',                    'NSE,BSE','Communication',        'Telecom'),
  ('KOTAKBANK',  'KOTAKBANK.NS',  'Kotak Mahindra Bank Ltd',              'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('ITC',        'ITC.NS',        'ITC Ltd',                              'NSE,BSE','FMCG',                 'Cigarettes & Tobacco'),
  ('LT',         'LT.NS',         'Larsen & Toubro Ltd',                  'NSE,BSE','Construction',         'Infrastructure'),
  ('SBIN',       'SBIN.NS',       'State Bank of India',                  'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('AXISBANK',   'AXISBANK.NS',   'Axis Bank Ltd',                        'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('BAJFINANCE', 'BAJFINANCE.NS', 'Bajaj Finance Ltd',                    'NSE,BSE','Financial Services',   'NBFC'),
  ('MARUTI',     'MARUTI.NS',     'Maruti Suzuki India Ltd',              'NSE,BSE','Automobile',           'Passenger Vehicles'),
  ('ASIANPAINT', 'ASIANPAINT.NS', 'Asian Paints Ltd',                     'NSE,BSE','Consumer Discretionary','Paints'),
  ('HCLTECH',    'HCLTECH.NS',    'HCL Technologies Ltd',                 'NSE,BSE','Technology',           'IT Services'),
  ('WIPRO',      'WIPRO.NS',      'Wipro Ltd',                            'NSE,BSE','Technology',           'IT Services'),
  ('NESTLEIND',  'NESTLEIND.NS',  'Nestle India Ltd',                     'NSE,BSE','FMCG',                 'Food Products'),
  ('SUNPHARMA',  'SUNPHARMA.NS',  'Sun Pharmaceutical Industries Ltd',    'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('ONGC',       'ONGC.NS',       'Oil & Natural Gas Corporation Ltd',    'NSE,BSE','Energy',               'Oil & Gas E&P'),
  ('NTPC',       'NTPC.NS',       'NTPC Ltd',                             'NSE,BSE','Utilities',            'Power Generation'),
  ('POWERGRID',  'POWERGRID.NS',  'Power Grid Corporation of India Ltd',  'NSE,BSE','Utilities',            'Power Transmission'),
  ('ADANIENT',   'ADANIENT.NS',   'Adani Enterprises Ltd',                'NSE,BSE','Diversified',          'Conglomerate'),
  ('ADANIPORTS', 'ADANIPORTS.NS', 'Adani Ports & SEZ Ltd',                'NSE,BSE','Industrials',          'Ports & Logistics'),
  ('TATAMOTORS', 'TATAMOTORS.NS', 'Tata Motors Ltd',                      'NSE,BSE','Automobile',           'Commercial Vehicles'),
  ('TATASTEEL',  'TATASTEEL.NS',  'Tata Steel Ltd',                       'NSE,BSE','Metals',               'Steel'),
  ('JSWSTEEL',   'JSWSTEEL.NS',   'JSW Steel Ltd',                        'NSE,BSE','Metals',               'Steel'),
  ('HINDALCO',   'HINDALCO.NS',   'Hindalco Industries Ltd',              'NSE,BSE','Metals',               'Aluminium'),
  ('COALINDIA',  'COALINDIA.NS',  'Coal India Ltd',                       'NSE,BSE','Energy',               'Coal Mining'),
  ('BPCL',       'BPCL.NS',       'Bharat Petroleum Corporation Ltd',     'NSE,BSE','Energy',               'Oil & Gas Refining'),
  ('TECHM',      'TECHM.NS',      'Tech Mahindra Ltd',                    'NSE,BSE','Technology',           'IT Services'),
  ('GRASIM',     'GRASIM.NS',     'Grasim Industries Ltd',                'NSE,BSE','Materials',            'Cement'),
  ('ULTRACEMCO', 'ULTRACEMCO.NS', 'UltraTech Cement Ltd',                 'NSE,BSE','Materials',            'Cement'),
  ('BAJAJFINSV', 'BAJAJFINSV.NS', 'Bajaj Finserv Ltd',                    'NSE,BSE','Financial Services',   'Insurance'),
  ('TITAN',      'TITAN.NS',      'Titan Company Ltd',                    'NSE,BSE','Consumer Discretionary','Watches & Jewelry'),
  ('DRREDDY',    'DRREDDY.NS',    'Dr Reddys Laboratories Ltd',           'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('BAJAJ-AUTO', 'BAJAJ-AUTO.NS', 'Bajaj Auto Ltd',                       'NSE,BSE','Automobile',           'Two Wheelers'),
  ('EICHERMOT',  'EICHERMOT.NS',  'Eicher Motors Ltd',                    'NSE,BSE','Automobile',           'Two Wheelers'),
  ('HEROMOTOCO', 'HEROMOTOCO.NS', 'Hero MotoCorp Ltd',                    'NSE,BSE','Automobile',           'Two Wheelers'),
  ('DIVISLAB',   'DIVISLAB.NS',   'Divis Laboratories Ltd',               'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('APOLLOHOSP', 'APOLLOHOSP.NS', 'Apollo Hospitals Enterprise Ltd',      'NSE,BSE','Healthcare',           'Hospitals'),
  ('HDFCLIFE',   'HDFCLIFE.NS',   'HDFC Life Insurance Co Ltd',           'NSE,BSE','Financial Services',   'Life Insurance'),
  ('SBILIFE',    'SBILIFE.NS',    'SBI Life Insurance Co Ltd',            'NSE,BSE','Financial Services',   'Life Insurance'),
  ('ICICIPRULI', 'ICICIPRULI.NS', 'ICICI Prudential Life Insurance',      'NSE,BSE','Financial Services',   'Life Insurance'),
  ('TATACONSUM', 'TATACONSUM.NS', 'Tata Consumer Products Ltd',           'NSE,BSE','FMCG',                 'Beverages'),
  ('BRITANNIA',  'BRITANNIA.NS',  'Britannia Industries Ltd',             'NSE,BSE','FMCG',                 'Food Products'),
  ('CIPLA',      'CIPLA.NS',      'Cipla Ltd',                            'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('SBICARD',    'SBICARD.NS',    'SBI Cards & Payment Services Ltd',     'NSE,BSE','Financial Services',   'Credit Cards'),
  ('INDUSINDBK', 'INDUSINDBK.NS', 'IndusInd Bank Ltd',                    'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('MM',         'M&M.NS',        'Mahindra & Mahindra Ltd',              'NSE,BSE','Automobile',           'SUV & Tractors'),

  -- NIFTY NEXT 50
  ('AMBUJACEM',  'AMBUJACEM.NS',  'Ambuja Cements Ltd',                   'NSE,BSE','Materials',            'Cement'),
  ('ACC',        'ACC.NS',        'ACC Ltd',                              'NSE,BSE','Materials',            'Cement'),
  ('AUROPHARMA', 'AUROPHARMA.NS', 'Aurobindo Pharma Ltd',                 'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('BANKBARODA', 'BANKBARODA.NS', 'Bank of Baroda',                       'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('BERGEPAINT', 'BERGEPAINT.NS', 'Berger Paints India Ltd',              'NSE,BSE','Consumer Discretionary','Paints'),
  ('BOSCHLTD',   'BOSCHLTD.NS',   'Bosch Ltd',                           'NSE,BSE','Automobile',           'Auto Components'),
  ('CANBK',      'CANBK.NS',      'Canara Bank',                          'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('COLPAL',     'COLPAL.NS',     'Colgate-Palmolive India Ltd',          'NSE,BSE','FMCG',                 'Personal Care'),
  ('DABUR',      'DABUR.NS',      'Dabur India Ltd',                      'NSE,BSE','FMCG',                 'Consumer Goods'),
  ('DLF',        'DLF.NS',        'DLF Ltd',                              'NSE,BSE','Real Estate',          'Residential'),
  ('GODREJCP',   'GODREJCP.NS',   'Godrej Consumer Products Ltd',         'NSE,BSE','FMCG',                 'Personal Care'),
  ('HAVELLS',    'HAVELLS.NS',    'Havells India Ltd',                    'NSE,BSE','Consumer Discretionary','Electrical Equipment'),
  ('ICICIGI',    'ICICIGI.NS',    'ICICI Lombard General Insurance',      'NSE,BSE','Financial Services',   'General Insurance'),
  ('INDUSTOWER', 'INDUSTOWER.NS', 'Indus Towers Ltd',                     'NSE,BSE','Communication',        'Telecom Infrastructure'),
  ('IOC',        'IOC.NS',        'Indian Oil Corporation Ltd',           'NSE,BSE','Energy',               'Oil & Gas Refining'),
  ('IRCTC',      'IRCTC.NS',      'Indian Railway Catering & Tourism',    'NSE,BSE','Industrials',          'Travel Services'),
  ('LICI',       'LICI.NS',       'Life Insurance Corporation of India',  'NSE,BSE','Financial Services',   'Life Insurance'),
  ('LUPIN',      'LUPIN.NS',      'Lupin Ltd',                            'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('MARICO',     'MARICO.NS',     'Marico Ltd',                           'NSE,BSE','FMCG',                 'Consumer Goods'),
  ('MCDOWELL-N', 'MCDOWELL-N.NS', 'United Spirits Ltd',                   'NSE,BSE','FMCG',                 'Beverages'),
  ('MUTHOOTFIN', 'MUTHOOTFIN.NS', 'Muthoot Finance Ltd',                  'NSE,BSE','Financial Services',   'NBFC'),
  ('NAUKRI',     'NAUKRI.NS',     'Info Edge India Ltd',                  'NSE,BSE','Technology',           'Internet Services'),
  ('NHPC',       'NHPC.NS',       'NHPC Ltd',                             'NSE,BSE','Utilities',            'Hydro Power'),
  ('OFSS',       'OFSS.NS',       'Oracle Financial Services Software',   'NSE,BSE','Technology',           'IT Services'),
  ('PAGEIND',    'PAGEIND.NS',    'Page Industries Ltd',                  'NSE,BSE','Consumer Discretionary','Garments'),
  ('PEL',        'PEL.NS',        'Piramal Enterprises Ltd',              'NSE,BSE','Diversified',          'Conglomerate'),
  ('PERSISTENT', 'PERSISTENT.NS', 'Persistent Systems Ltd',               'NSE,BSE','Technology',           'IT Services'),
  ('PETRONET',   'PETRONET.NS',   'Petronet LNG Ltd',                     'NSE,BSE','Energy',               'LNG'),
  ('PIIND',      'PIIND.NS',      'PI Industries Ltd',                    'NSE,BSE','Chemicals',            'Agrochemicals'),
  ('PIDILITIND', 'PIDILITIND.NS', 'Pidilite Industries Ltd',              'NSE,BSE','Chemicals',            'Adhesives'),
  ('PNB',        'PNB.NS',        'Punjab National Bank',                 'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('POLYCAB',    'POLYCAB.NS',    'Polycab India Ltd',                    'NSE,BSE','Consumer Discretionary','Cables & Wires'),
  ('RECLTD',     'RECLTD.NS',     'REC Ltd',                              'NSE,BSE','Financial Services',   'Power Finance'),
  ('SHRIRAMFIN', 'SHRIRAMFIN.NS', 'Shriram Finance Ltd',                  'NSE,BSE','Financial Services',   'NBFC'),
  ('SIEMENS',    'SIEMENS.NS',    'Siemens Ltd',                          'NSE,BSE','Industrials',          'Electrical Equipment'),
  ('TORNTPHARM', 'TORNTPHARM.NS', 'Torrent Pharmaceuticals Ltd',          'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('TRENT',      'TRENT.NS',      'Trent Ltd',                            'NSE,BSE','Consumer Discretionary','Retail'),
  ('TVSMOTOR',   'TVSMOTOR.NS',   'TVS Motor Company Ltd',                'NSE,BSE','Automobile',           'Two Wheelers'),
  ('UPL',        'UPL.NS',        'UPL Ltd',                              'NSE,BSE','Chemicals',            'Agrochemicals'),
  ('VBL',        'VBL.NS',        'Varun Beverages Ltd',                  'NSE,BSE','FMCG',                 'Beverages'),
  ('VEDL',       'VEDL.NS',       'Vedanta Ltd',                          'NSE,BSE','Metals',               'Diversified Metals'),
  ('ZOMATO',     'ZOMATO.NS',     'Zomato Ltd',                           'NSE,BSE','Consumer Discretionary','Food Delivery'),
  ('NYKAA',      'NYKAA.NS',      'FSN E-Commerce Ventures Nykaa',        'NSE,BSE','Consumer Discretionary','E-Commerce'),
  ('PAYTM',      'PAYTM.NS',      'One97 Communications Paytm',           'NSE,BSE','Technology',           'Fintech'),
  ('POLICYBZR',  'POLICYBZR.NS',  'PB Fintech PolicyBazaar',              'NSE,BSE','Technology',           'Fintech'),

  -- IT & TECH
  ('MPHASIS',    'MPHASIS.NS',    'Mphasis Ltd',                          'NSE,BSE','Technology',           'IT Services'),
  ('LTIM',       'LTIM.NS',       'LTIMindtree Ltd',                      'NSE,BSE','Technology',           'IT Services'),
  ('LTTS',       'LTTS.NS',       'L&T Technology Services Ltd',          'NSE,BSE','Technology',           'IT Services'),
  ('COFORGE',    'COFORGE.NS',    'Coforge Ltd',                          'NSE,BSE','Technology',           'IT Services'),
  ('KPITTECH',   'KPITTECH.NS',   'KPIT Technologies Ltd',                'NSE,BSE','Technology',           'IT Services'),
  ('HAPPSTMNDS', 'HAPPSTMNDS.NS', 'Happiest Minds Technologies Ltd',      'NSE,BSE','Technology',           'IT Services'),
  ('TANLA',      'TANLA.NS',      'Tanla Platforms Ltd',                  'NSE,BSE','Technology',           'Cloud Communications'),
  ('MAPMYINDIA', 'MAPMYINDIA.NS', 'C.E. Info Systems MapMyIndia',         'NSE,BSE','Technology',           'Navigation'),
  ('TATAELXSI',  'TATAELXSI.NS',  'Tata Elxsi Ltd',                      'NSE,BSE','Technology',           'Design & Engineering'),
  ('JUSTDIAL',   'JUSTDIAL.NS',   'Just Dial Ltd',                        'NSE,BSE','Technology',           'Internet Services'),
  ('AFFLE',      'AFFLE.NS',      'Affle India Ltd',                      'NSE,BSE','Technology',           'Ad Tech'),
  ('INDIAMART',  'INDIAMART.NS',  'IndiaMART InterMESH Ltd',              'NSE,BSE','Technology',           'B2B Marketplace'),
  ('CARTRADE',   'CARTRADE.NS',   'CarTrade Tech Ltd',                    'NSE,BSE','Technology',           'Auto Classifieds'),

  -- BANKING & FINANCIAL
  ('FEDERALBNK', 'FEDERALBNK.NS', 'Federal Bank Ltd',                     'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('IDFCFIRSTB', 'IDFCFIRSTB.NS', 'IDFC FIRST Bank Ltd',                  'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('RBLBANK',    'RBLBANK.NS',    'RBL Bank Ltd',                         'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('YESBANK',    'YESBANK.NS',    'Yes Bank Ltd',                         'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('BANDHANBNK', 'BANDHANBNK.NS', 'Bandhan Bank Ltd',                     'NSE,BSE','Financial Services',   'Private Sector Bank'),
  ('AUBANK',     'AUBANK.NS',     'AU Small Finance Bank Ltd',            'NSE,BSE','Financial Services',   'Small Finance Bank'),
  ('UJJIVANSFB', 'UJJIVANSFB.NS', 'Ujjivan Small Finance Bank Ltd',       'NSE,BSE','Financial Services',   'Small Finance Bank'),
  ('EQUITASBNK', 'EQUITASBNK.NS', 'Equitas Small Finance Bank Ltd',       'NSE,BSE','Financial Services',   'Small Finance Bank'),
  ('UNIONBANK',  'UNIONBANK.NS',  'Union Bank of India',                  'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('IOB',        'IOB.NS',        'Indian Overseas Bank',                 'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('MAHABANK',   'MAHABANK.NS',   'Bank of Maharashtra',                  'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('CENTRALBK',  'CENTRALBK.NS',  'Central Bank of India',                'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('INDIANB',    'INDIANB.NS',    'Indian Bank',                          'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('PSB',        'PSB.NS',        'Punjab & Sind Bank',                   'NSE,BSE','Financial Services',   'Public Sector Bank'),
  ('BAJAJHLDNG', 'BAJAJHLDNG.NS', 'Bajaj Holdings & Investment Ltd',      'NSE,BSE','Financial Services',   'Investment Company'),
  ('LICHSGFIN',  'LICHSGFIN.NS',  'LIC Housing Finance Ltd',              'NSE,BSE','Financial Services',   'Housing Finance'),
  ('PNBHOUSING', 'PNBHOUSING.NS', 'PNB Housing Finance Ltd',              'NSE,BSE','Financial Services',   'Housing Finance'),
  ('CANFINHOME', 'CANFINHOME.NS', 'Can Fin Homes Ltd',                    'NSE,BSE','Financial Services',   'Housing Finance'),
  ('HOMEFIRST',  'HOMEFIRST.NS',  'Home First Finance Co India Ltd',      'NSE,BSE','Financial Services',   'Housing Finance'),
  ('CHOLAFIN',   'CHOLAFIN.NS',   'Cholamandalam Investment & Finance',   'NSE,BSE','Financial Services',   'NBFC'),
  ('MMFIN',      'M&MFIN.NS',     'Mahindra & Mahindra Financial Svc',   'NSE,BSE','Financial Services',   'NBFC'),
  ('SUNDARMFIN', 'SUNDARMFIN.NS', 'Sundaram Finance Ltd',                 'NSE,BSE','Financial Services',   'NBFC'),
  ('MANAPPURAM', 'MANAPPURAM.NS', 'Manappuram Finance Ltd',               'NSE,BSE','Financial Services',   'NBFC'),
  ('MOTILALOFS', 'MOTILALOFS.NS', 'Motilal Oswal Financial Services',     'NSE,BSE','Financial Services',   'Broking'),
  ('ANGELONE',   'ANGELONE.NS',   'Angel One Ltd',                        'NSE,BSE','Financial Services',   'Broking'),
  ('360ONE',     '360ONE.NS',     '360 ONE WAM Ltd',                      'NSE,BSE','Financial Services',   'Wealth Management'),
  ('NUVAMA',     'NUVAMA.NS',     'Nuvama Wealth Management Ltd',         'NSE,BSE','Financial Services',   'Wealth Management'),
  ('IIFL',       'IIFL.NS',       'IIFL Finance Ltd',                     'NSE,BSE','Financial Services',   'NBFC'),
  ('ISEC',       'ISEC.NS',       'ICICI Securities Ltd',                 'NSE,BSE','Financial Services',   'Broking'),
  ('PFC',        'PFC.NS',        'Power Finance Corporation Ltd',        'NSE,BSE','Financial Services',   'Power Finance'),
  ('GICRE',      'GICRE.NS',      'General Insurance Corp of India',      'NSE,BSE','Financial Services',   'General Insurance'),
  ('NIACL',      'NIACL.NS',      'New India Assurance Co Ltd',           'NSE,BSE','Financial Services',   'General Insurance'),
  ('STARHEALTH', 'STARHEALTH.NS', 'Star Health & Allied Insurance',       'NSE,BSE','Financial Services',   'Health Insurance'),

  -- PHARMA & HEALTHCARE
  ('ALKEM',      'ALKEM.NS',      'Alkem Laboratories Ltd',               'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('BIOCON',     'BIOCON.NS',     'Biocon Ltd',                           'NSE,BSE','Healthcare',           'Biopharmaceuticals'),
  ('GLENMARK',   'GLENMARK.NS',   'Glenmark Pharmaceuticals Ltd',         'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('GRANULES',   'GRANULES.NS',   'Granules India Ltd',                   'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('IPCALAB',    'IPCALAB.NS',    'IPCA Laboratories Ltd',                'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('NATCOPHARM', 'NATCOPHARM.NS', 'Natco Pharma Ltd',                     'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('LALPATHLAB', 'LALPATHLAB.NS', 'Dr. Lal PathLabs Ltd',                 'NSE,BSE','Healthcare',           'Diagnostics'),
  ('METROPOLIS', 'METROPOLIS.NS', 'Metropolis Healthcare Ltd',            'NSE,BSE','Healthcare',           'Diagnostics'),
  ('MAXHEALTH',  'MAXHEALTH.NS',  'Max Healthcare Institute Ltd',         'NSE,BSE','Healthcare',           'Hospitals'),
  ('NH',         'NH.NS',         'Narayana Hrudayalaya Ltd',             'NSE,BSE','Healthcare',           'Hospitals'),
  ('ERIS',       'ERIS.NS',       'Eris Lifesciences Ltd',                'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('JBCHEPHARM', 'JBCHEPHARM.NS', 'JB Chemicals & Pharmaceuticals Ltd',   'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('ZYDUSLIFE',  'ZYDUSLIFE.NS',  'Zydus Lifesciences Ltd',               'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('ABBOTINDIA', 'ABBOTINDIA.NS', 'Abbott India Ltd',                     'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('PFIZER',     'PFIZER.NS',     'Pfizer Ltd',                           'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('SANOFI',     'SANOFI.NS',     'Sanofi India Ltd',                     'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('SOLARA',     'SOLARA.NS',     'Solara Active Pharma Sciences Ltd',    'NSE,BSE','Healthcare',           'Pharmaceuticals'),
  ('YATHARTH',   'YATHARTH.NS',   'Yatharth Hospital & Trauma Care',      'NSE,BSE','Healthcare',           'Hospitals'),
  ('KRSNAA',     'KRSNAA.NS',     'Krsnaa Diagnostics Ltd',               'NSE,BSE','Healthcare',           'Diagnostics'),

  -- AUTOMOBILE
  ('ASHOKLEY',   'ASHOKLEY.NS',   'Ashok Leyland Ltd',                    'NSE,BSE','Automobile',           'Commercial Vehicles'),
  ('EXIDEIND',   'EXIDEIND.NS',   'Exide Industries Ltd',                 'NSE,BSE','Automobile',           'Auto Components'),
  ('MOTHERSON',  'MOTHERSON.NS',  'Samvardhana Motherson International',  'NSE,BSE','Automobile',           'Auto Components'),
  ('BHARATFORG', 'BHARATFORG.NS', 'Bharat Forge Ltd',                     'NSE,BSE','Automobile',           'Auto Components'),
  ('BALKRISIND', 'BALKRISIND.NS', 'Balkrishna Industries Ltd',            'NSE,BSE','Automobile',           'Tyres'),
  ('MRF',        'MRF.NS',        'MRF Ltd',                              'NSE,BSE','Automobile',           'Tyres'),
  ('APOLLOTYRE', 'APOLLOTYRE.NS', 'Apollo Tyres Ltd',                     'NSE,BSE','Automobile',           'Tyres'),
  ('CEATLTD',    'CEATLTD.NS',    'CEAT Ltd',                             'NSE,BSE','Automobile',           'Tyres'),
  ('OLECTRA',    'OLECTRA.NS',    'Olectra Greentech Ltd',                'NSE,BSE','Automobile',           'Electric Vehicles'),
  ('MAHINDCIE',  'MAHINDCIE.NS',  'Mahindra CIE Automotive Ltd',          'NSE,BSE','Automobile',           'Auto Components'),

  -- ENERGY & POWER
  ('ADANIGREEN', 'ADANIGREEN.NS', 'Adani Green Energy Ltd',               'NSE,BSE','Utilities',            'Renewable Energy'),
  ('ADANIPOWER', 'ADANIPOWER.NS', 'Adani Power Ltd',                      'NSE,BSE','Utilities',            'Power Generation'),
  ('TATAPOWER',  'TATAPOWER.NS',  'Tata Power Co Ltd',                    'NSE,BSE','Utilities',            'Power Generation'),
  ('TORNTPOWER', 'TORNTPOWER.NS', 'Torrent Power Ltd',                    'NSE,BSE','Utilities',            'Power Generation'),
  ('CESC',       'CESC.NS',       'CESC Ltd',                             'NSE,BSE','Utilities',            'Power Utility'),
  ('SUZLON',     'SUZLON.NS',     'Suzlon Energy Ltd',                    'NSE,BSE','Utilities',            'Wind Energy'),
  ('INOXWIND',   'INOXWIND.NS',   'Inox Wind Ltd',                        'NSE,BSE','Utilities',            'Wind Energy'),
  ('SJVN',       'SJVN.NS',       'SJVN Ltd',                             'NSE,BSE','Utilities',            'Hydro Power'),
  ('THERMAX',    'THERMAX.NS',    'Thermax Ltd',                          'NSE,BSE','Industrials',          'Energy Equipment'),
  ('GAIL',       'GAIL.NS',       'GAIL India Ltd',                       'NSE,BSE','Energy',               'Natural Gas'),
  ('IGL',        'IGL.NS',        'Indraprastha Gas Ltd',                 'NSE,BSE','Energy',               'City Gas'),
  ('MGL',        'MGL.NS',        'Mahanagar Gas Ltd',                    'NSE,BSE','Energy',               'City Gas'),
  ('HINDPETRO',  'HINDPETRO.NS',  'Hindustan Petroleum Corp Ltd',         'NSE,BSE','Energy',               'Oil & Gas Refining'),
  ('MRPL',       'MRPL.NS',       'Mangalore Refinery & Petrochemicals',  'NSE,BSE','Energy',               'Oil & Gas Refining'),
  ('CASTROLIND', 'CASTROLIND.NS', 'Castrol India Ltd',                    'NSE,BSE','Energy',               'Lubricants'),
  ('AEGISCHEM',  'AEGISCHEM.NS',  'Aegis Logistics Ltd',                  'NSE,BSE','Energy',               'LPG Logistics'),
  ('TATACHEM',   'TATACHEM.NS',   'Tata Chemicals Ltd',                   'NSE,BSE','Chemicals',            'Specialty Chemicals'),

  -- METALS & MINING
  ('SAIL',       'SAIL.NS',       'Steel Authority of India Ltd',         'NSE,BSE','Metals',               'Steel'),
  ('NMDC',       'NMDC.NS',       'NMDC Ltd',                             'NSE,BSE','Metals',               'Iron Ore Mining'),
  ('NATIONALUM', 'NATIONALUM.NS', 'National Aluminium Co Ltd',            'NSE,BSE','Metals',               'Aluminium'),
  ('HINDCOPPER', 'HINDCOPPER.NS', 'Hindustan Copper Ltd',                 'NSE,BSE','Metals',               'Copper'),
  ('MOIL',       'MOIL.NS',       'MOIL Ltd',                             'NSE,BSE','Metals',               'Manganese Ore'),
  ('APLAPOLLO',  'APLAPOLLO.NS',  'APL Apollo Tubes Ltd',                 'NSE,BSE','Metals',               'Steel Tubes'),
  ('RATNAMANI',  'RATNAMANI.NS',  'Ratnamani Metals & Tubes Ltd',         'NSE,BSE','Metals',               'Steel Tubes'),
  ('WELCORP',    'WELCORP.NS',    'Welspun Corp Ltd',                     'NSE,BSE','Metals',               'Steel Pipes'),
  ('JSPL',       'JSPL.NS',       'Jindal Steel & Power Ltd',             'NSE,BSE','Metals',               'Steel'),
  ('JINDALSAW',  'JINDALSAW.NS',  'Jindal Saw Ltd',                       'NSE,BSE','Metals',               'Steel Pipes'),

  -- CHEMICALS
  ('SRF',        'SRF.NS',        'SRF Ltd',                              'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('DEEPAKNTR',  'DEEPAKNTR.NS',  'Deepak Nitrite Ltd',                   'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('NAVINFLUOR', 'NAVINFLUOR.NS', 'Navin Fluorine International Ltd',     'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('AARTI',      'AARTI.NS',      'Aarti Industries Ltd',                 'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('GALAXYSURF', 'GALAXYSURF.NS', 'Galaxy Surfactants Ltd',               'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('VINATIORGA', 'VINATIORGA.NS', 'Vinati Organics Ltd',                  'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('SUDARSCHEM', 'SUDARSCHEM.NS', 'Sudarshan Chemical Industries Ltd',    'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('ATUL',       'ATUL.NS',       'Atul Ltd',                             'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('NOCIL',      'NOCIL.NS',      'NOCIL Ltd',                            'NSE,BSE','Chemicals',            'Rubber Chemicals'),
  ('ROSSARI',    'ROSSARI.NS',    'Rossari Biotech Ltd',                  'NSE,BSE','Chemicals',            'Specialty Chemicals'),
  ('FINEORG',    'FINEORG.NS',    'Fine Organic Industries Ltd',          'NSE,BSE','Chemicals',            'Food Additives'),
  ('CHAMBLFERT', 'CHAMBLFERT.NS', 'Chambal Fertilisers & Chemicals Ltd',  'NSE,BSE','Chemicals',            'Fertilizers'),
  ('COROMANDEL', 'COROMANDEL.NS', 'Coromandel International Ltd',         'NSE,BSE','Chemicals',            'Fertilizers'),
  ('GNFC',       'GNFC.NS',       'Gujarat Narmada Valley Fertilizers',   'NSE,BSE','Chemicals',            'Fertilizers'),
  ('NFL',        'NFL.NS',        'National Fertilizers Ltd',             'NSE,BSE','Chemicals',            'Fertilizers'),
  ('RCF',        'RCF.NS',        'Rashtriya Chemicals & Fertilizers',    'NSE,BSE','Chemicals',            'Fertilizers'),

  -- REAL ESTATE & INFRA
  ('OBEROIRLTY', 'OBEROIRLTY.NS', 'Oberoi Realty Ltd',                    'NSE,BSE','Real Estate',          'Residential'),
  ('GODREJPROP', 'GODREJPROP.NS', 'Godrej Properties Ltd',                'NSE,BSE','Real Estate',          'Residential'),
  ('PRESTIGE',   'PRESTIGE.NS',   'Prestige Estates Projects Ltd',        'NSE,BSE','Real Estate',          'Residential'),
  ('PHOENIXLTD', 'PHOENIXLTD.NS', 'The Phoenix Mills Ltd',                'NSE,BSE','Real Estate',          'Commercial'),
  ('SOBHA',      'SOBHA.NS',      'Sobha Ltd',                            'NSE,BSE','Real Estate',          'Residential'),
  ('BRIGADE',    'BRIGADE.NS',    'Brigade Enterprises Ltd',              'NSE,BSE','Real Estate',          'Residential'),
  ('MACROTECH',  'LODHA.NS',      'Macrotech Developers Ltd Lodha',       'NSE,BSE','Real Estate',          'Residential'),
  ('MAHLIFE',    'MAHLIFE.NS',    'Mahindra Lifespace Developers Ltd',    'NSE,BSE','Real Estate',          'Residential'),
  ('GMRINFRA',   'GMRINFRA.NS',   'GMR Airports Infrastructure Ltd',      'NSE,BSE','Industrials',          'Airports'),
  ('IRB',        'IRB.NS',        'IRB Infrastructure Developers Ltd',    'NSE,BSE','Industrials',          'Roads'),
  ('KNRCON',     'KNRCON.NS',     'KNR Constructions Ltd',                'NSE,BSE','Industrials',          'Roads'),
  ('NCC',        'NCC.NS',        'NCC Ltd',                              'NSE,BSE','Industrials',          'Construction'),
  ('HGINFRA',    'HGINFRA.NS',    'H.G. Infra Engineering Ltd',           'NSE,BSE','Industrials',          'Roads'),

  -- CONSUMER & RETAIL
  ('DMART',      'DMART.NS',      'Avenue Supermarts Ltd D-Mart',         'NSE,BSE','Consumer Discretionary','Retail'),
  ('VMART',      'VMART.NS',      'V-Mart Retail Ltd',                    'NSE,BSE','Consumer Discretionary','Retail'),
  ('SHOPERSTOP', 'SHOPERSTOP.NS', 'Shoppers Stop Ltd',                    'NSE,BSE','Consumer Discretionary','Retail'),
  ('RAYMOND',    'RAYMOND.NS',    'Raymond Ltd',                          'NSE,BSE','Consumer Discretionary','Textiles'),
  ('MANYAVAR',   'MANYAVAR.NS',   'Vedant Fashions Ltd Manyavar',         'NSE,BSE','Consumer Discretionary','Apparel'),
  ('BATA',       'BATA.NS',       'Bata India Ltd',                       'NSE,BSE','Consumer Discretionary','Footwear'),
  ('RELAXO',     'RELAXO.NS',     'Relaxo Footwears Ltd',                 'NSE,BSE','Consumer Discretionary','Footwear'),
  ('VOLTAS',     'VOLTAS.NS',     'Voltas Ltd',                           'NSE,BSE','Consumer Discretionary','AC & Refrigeration'),
  ('BLUESTARCO', 'BLUESTARCO.NS', 'Blue Star Ltd',                        'NSE,BSE','Consumer Discretionary','AC & Refrigeration'),
  ('CROMPTON',   'CROMPTON.NS',   'Crompton Greaves Consumer Electricals','NSE,BSE','Consumer Discretionary','Electrical Appliances'),
  ('VGUARD',     'VGUARD.NS',     'V-Guard Industries Ltd',               'NSE,BSE','Consumer Discretionary','Electrical Equipment'),
  ('SYMPHONY',   'SYMPHONY.NS',   'Symphony Ltd',                         'NSE,BSE','Consumer Discretionary','Air Coolers'),
  ('EMAMILTD',   'EMAMILTD.NS',   'Emami Ltd',                            'NSE,BSE','FMCG',                 'Personal Care'),
  ('JYOTHYLAB',  'JYOTHYLAB.NS',  'Jyothy Labs Ltd',                      'NSE,BSE','FMCG',                 'Personal Care'),
  ('BAJAJCON',   'BAJAJCON.NS',   'Bajaj Consumer Care Ltd',              'NSE,BSE','FMCG',                 'Personal Care'),
  ('RADICO',     'RADICO.NS',     'Radico Khaitan Ltd',                   'NSE,BSE','FMCG',                 'Beverages'),
  ('KRBL',       'KRBL.NS',       'KRBL Ltd',                             'NSE,BSE','FMCG',                 'Food Products'),
  ('LTFOODS',    'LTFOODS.NS',    'LT Foods Ltd',                         'NSE,BSE','FMCG',                 'Food Products'),
  ('AVANTIFEED', 'AVANTIFEED.NS', 'Avanti Feeds Ltd',                     'NSE,BSE','FMCG',                 'Aquaculture'),
  ('TATACOFFEE', 'TATACOFFEE.NS', 'Tata Coffee Ltd',                      'NSE,BSE','FMCG',                 'Beverages'),
  ('VSTIND',     'VSTIND.NS',     'VST Industries Ltd',                   'NSE,BSE','FMCG',                 'Cigarettes'),

  -- INDUSTRIALS
  ('ABB',        'ABB.NS',        'ABB India Ltd',                        'NSE,BSE','Industrials',          'Electrical Equipment'),
  ('CUMMINSIND', 'CUMMINSIND.NS', 'Cummins India Ltd',                    'NSE,BSE','Industrials',          'Engines'),
  ('HONAUT',     'HONAUT.NS',     'Honeywell Automation India Ltd',       'NSE,BSE','Industrials',          'Automation'),
  ('BLUEDART',   'BLUEDART.NS',   'Blue Dart Express Ltd',                'NSE,BSE','Industrials',          'Courier'),
  ('DELHIVERY',  'DELHIVERY.NS',  'Delhivery Ltd',                        'NSE,BSE','Industrials',          'Logistics'),
  ('MTARTECH',   'MTARTECH.NS',   'MTAR Technologies Ltd',                'NSE,BSE','Industrials',          'Precision Engineering'),

  -- DEFENCE
  ('HAL',        'HAL.NS',        'Hindustan Aeronautics Ltd',            'NSE,BSE','Industrials',          'Defence Aerospace'),
  ('BEL',        'BEL.NS',        'Bharat Electronics Ltd',               'NSE,BSE','Industrials',          'Defence Electronics'),
  ('BEML',       'BEML.NS',       'BEML Ltd',                             'NSE,BSE','Industrials',          'Heavy Equipment'),
  ('COCHINSHIP', 'COCHINSHIP.NS', 'Cochin Shipyard Ltd',                  'NSE,BSE','Industrials',          'Shipbuilding'),
  ('MAZDOCK',    'MAZDOCK.NS',    'Mazagon Dock Shipbuilders Ltd',        'NSE,BSE','Industrials',          'Shipbuilding'),
  ('GRSE',       'GRSE.NS',       'Garden Reach Shipbuilders & Eng',      'NSE,BSE','Industrials',          'Shipbuilding'),

  -- TELECOM
  ('IDEA',       'IDEA.NS',       'Vodafone Idea Ltd',                    'NSE,BSE','Communication',        'Telecom'),
  ('TATACOMM',   'TATACOMM.NS',   'Tata Communications Ltd',              'NSE,BSE','Communication',        'Data Services'),
  ('HFCL',       'HFCL.NS',       'HFCL Ltd',                             'NSE,BSE','Communication',        'Telecom Equipment'),
  ('TEJASNET',   'TEJASNET.NS',   'Tejas Networks Ltd',                   'NSE,BSE','Communication',        'Telecom Equipment'),

  -- MEDIA
  ('ZEEL',       'ZEEL.NS',       'Zee Entertainment Enterprises Ltd',    'NSE,BSE','Media',                'Television'),
  ('SUNTV',      'SUNTV.NS',      'Sun TV Network Ltd',                   'NSE,BSE','Media',                'Television'),
  ('PVRINOX',    'PVRINOX.NS',    'PVR INOX Ltd',                         'NSE,BSE','Media',                'Movie Exhibition'),
  ('NAZARA',     'NAZARA.NS',     'Nazara Technologies Ltd',              'NSE,BSE','Media',                'Gaming'),
  ('SAREGAMA',   'SAREGAMA.NS',   'Saregama India Ltd',                   'NSE,BSE','Media',                'Music'),

  -- TRAVEL
  ('EASEMYTRIP', 'EASEMYTRIP.NS', 'Easy Trip Planners Ltd',               'NSE,BSE','Consumer Discretionary','Online Travel'),

  -- BSE-SPECIFIC (.BO suffix)
  ('RELIANCE',   'RELIANCE.BO',   'Reliance Industries Ltd BSE',          'BSE',     'Energy',               'Oil & Gas Refining'),
  ('TCS',        'TCS.BO',        'TCS Ltd BSE',                          'BSE',     'Technology',           'IT Services'),
  ('HDFCBANK',   'HDFCBANK.BO',   'HDFC Bank Ltd BSE',                    'BSE',     'Financial Services',   'Private Sector Bank'),
  ('INFY',       'INFY.BO',       'Infosys Ltd BSE',                      'BSE',     'Technology',           'IT Services'),
  ('ICICIBANK',  'ICICIBANK.BO',  'ICICI Bank Ltd BSE',                   'BSE',     'Financial Services',   'Private Sector Bank'),
  ('TATAMOTORS', 'TATAMOTORS.BO', 'Tata Motors Ltd BSE',                  'BSE',     'Automobile',           'Commercial Vehicles'),
  ('WIPRO',      'WIPRO.BO',      'Wipro Ltd BSE',                        'BSE',     'Technology',           'IT Services'),
  ('MARUTI',     'MARUTI.BO',     'Maruti Suzuki India Ltd BSE',          'BSE',     'Automobile',           'Passenger Vehicles'),
  ('SBIN',       'SBIN.BO',       'State Bank of India BSE',              'BSE',     'Financial Services',   'Public Sector Bank'),
  ('BAJFINANCE', 'BAJFINANCE.BO', 'Bajaj Finance Ltd BSE',                'BSE',     'Financial Services',   'NBFC'),
  ('ADANIENT',   'ADANIENT.BO',   'Adani Enterprises Ltd BSE',            'BSE',     'Diversified',          'Conglomerate'),
  ('LTIM',       'LTIM.BO',       'LTIMindtree Ltd BSE',                  'BSE',     'Technology',           'IT Services'),
  ('SUNPHARMA',  'SUNPHARMA.BO',  'Sun Pharma Industries Ltd BSE',        'BSE',     'Healthcare',           'Pharmaceuticals'),
  ('ULTRACEMCO', 'ULTRACEMCO.BO', 'UltraTech Cement Ltd BSE',             'BSE',     'Materials',            'Cement'),
  ('NTPC',       'NTPC.BO',       'NTPC Ltd BSE',                         'BSE',     'Utilities',            'Power Generation'),
  ('LICI',       'LICI.BO',       'LIC of India BSE',                     'BSE',     'Financial Services',   'Life Insurance'),
  ('DLF',        'DLF.BO',        'DLF Ltd BSE',                          'BSE',     'Real Estate',          'Residential'),
  ('HINDUNILVR', 'HINDUNILVR.BO', 'Hindustan Unilever Ltd BSE',           'BSE',     'FMCG',                 'Consumer Goods'),
  ('COALINDIA',  'COALINDIA.BO',  'Coal India Ltd BSE',                   'BSE',     'Energy',               'Coal Mining'),
  ('ZOMATO',     'ZOMATO.BO',     'Zomato Ltd BSE',                       'BSE',     'Consumer Discretionary','Food Delivery')
),
deduped AS (
  SELECT DISTINCT ON (yahoo_symbol) symbol, yahoo_symbol, company_name, exchange, sector, industry
  FROM raw_data
  ORDER BY yahoo_symbol
)
INSERT INTO indian_stocks (symbol, yahoo_symbol, company_name, exchange, sector, industry)
SELECT * FROM deduped
ON CONFLICT (yahoo_symbol) DO UPDATE SET
  company_name = EXCLUDED.company_name,
  sector       = EXCLUDED.sector,
  industry     = EXCLUDED.industry;

-- Verify result
SELECT exchange, COUNT(*) AS total FROM indian_stocks GROUP BY exchange ORDER BY exchange;
